//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ql_khachhang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAO_CAO
    {
        public string MABC { get; set; }
        public System.DateTime NGAYLAP { get; set; }
        public Nullable<decimal> DOANHTHU { get; set; }
        public Nullable<int> SOLUONGKH { get; set; }
        public Nullable<int> SOLUONGLICH { get; set; }
        public string GHICHU { get; set; }
        public string LOAI_BC { get; set; }
        public Nullable<System.DateTime> NGAY_BATDAU { get; set; }
        public Nullable<System.DateTime> NGAY_KETTHUC { get; set; }
    }
}
