//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ql_khachhang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHAN_VIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHAN_VIEN()
        {
            this.LICH_HEN = new HashSet<LICH_HEN>();
        }
    
        public string MANV { get; set; }
        public string HOTEN { get; set; }
        public string CHUCVU { get; set; }
        public Nullable<decimal> LUONG { get; set; }
        public string MACHINHANH { get; set; }
    
        public virtual CHI_NHANH CHI_NHANH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICH_HEN> LICH_HEN { get; set; }
    }
}
