//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ql_khachhang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHAN_HOI
    {
        public string MAPH { get; set; }
        public string MAKH { get; set; }
        public string MADV { get; set; }
        public string NOIDUNG { get; set; }
        public Nullable<int> DANHGIA { get; set; }
        public Nullable<System.DateTime> NGAYPH { get; set; }
    
        public virtual DICH_VU DICH_VU { get; set; }
        public virtual KHACH_HANG KHACH_HANG { get; set; }
    }
}
