//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ql_khachhang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANH_TOAN
    {
        public string MATT { get; set; }
        public string MAKH { get; set; }
        public System.DateTime NGAYTT { get; set; }
        public decimal TONGTIEN { get; set; }
        public string PHUONGTHUC { get; set; }
        public string MAKM { get; set; }
    
        public virtual KHACH_HANG KHACH_HANG { get; set; }
        public virtual KHUYEN_MAI KHUYEN_MAI { get; set; }
    }
}
